/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-CPP-Markdown.h
 #	source generated by 4D Plugin Wizard
 #	Project : CPP Markdown
 #	author : miyako
 #	2019/12/13
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_CPP_MARKDOWN_H
#define PLUGIN_CPP_MARKDOWN_H

#include "4DPluginAPI.h"

#include "C_TEXT.h"

#include <iostream>
#include <sstream>
#include <fstream>
#include <vector>
#include <string>

#include "markdown.h"

#include <boost/optional.hpp>
#include <boost/regex.hpp>

#pragma mark -

void CPP_Markdown(PA_PluginParameters params);

#endif /* PLUGIN_CPP_MARKDOWN_H */
