/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : CPP Markdown
 #	author : miyako
 #	2013/10/21
 #
 # --------------------------------------------------------------------------------*/

#include "4DPluginAPI.h"

#include <iostream>
#include <sstream>
#include <fstream>
#include <vector>
#include <string>

#include <boost/optional.hpp>
#include <boost/regex.hpp>

#include "markdown.h"

// --- CPP Markdown
void CPP_Markdown(sLONG_PTR *pResult, PackagePtr pParams);
