/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.c
 #	source generated by 4D Plugin Wizard
 #	Project : CPP Markdown
 #	author : miyako
 #	2013/10/21
 #
 # --------------------------------------------------------------------------------*/

#include "4DPlugin.h"

void PluginMain(int32_t selector, PA_PluginParameters params)
{
	try
	{
		int32_t pProcNum = selector;
		sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
		PackagePtr pParams = (PackagePtr)params->fParameters;

		CommandDispatcher(pProcNum, pResult, pParams); 
	}
	catch(...)
	{

	}
}

void CommandDispatcher (int32_t pProcNum, sLONG_PTR *pResult, PackagePtr pParams)
{
	switch(pProcNum)
	{
// --- CPP Markdown

		case 1 :
			CPP_Markdown(pResult, pParams);
			break;

	}
}

// --------------------------------- CPP Markdown ---------------------------------


void CPP_Markdown(sLONG_PTR *pResult, PackagePtr pParams)
{
	C_TEXT Param1;
	C_TEXT returnValue;

	Param1.fromParamAtIndex(pParams, 1);

	CUTF8String u;
	Param1.copyUTF8String(&u);

	markdown::Document doc;
	
	std::istringstream instream(std::string((const char *)u.c_str(), u.length()));
	doc.read(instream);
	
	std::ostringstream outstream;
	doc.write(outstream);
	
	std::string dst = outstream.str();
	returnValue.setUTF8String((const uint8_t *)dst.c_str(), dst.length());
	
	returnValue.setReturn(pResult);
}

