/* --------------------------------------------------------------------------------
 #
 #  4DPlugin-CPP-Markdown.cpp
 #	source generated by 4D Plugin Wizard
 #	Project : CPP Markdown
 #	author : miyako
 #	2019/12/13
 #  
 # --------------------------------------------------------------------------------*/

#include "4DPlugin-CPP-Markdown.h"

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params) {
    
	try
	{
        switch(selector)
        {
			// --- CPP Markdown
            
			case 1 :
				CPP_Markdown(params);
				break;

        }

	}
	catch(...)
	{

	}
}

#pragma mark -

void CPP_Markdown(PA_PluginParameters params) {
    
    sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
    PackagePtr pParams = (PackagePtr)params->fParameters;

    C_TEXT Param1;
    C_TEXT returnValue;

    Param1.fromParamAtIndex(pParams, 1);

    CUTF8String u;
    Param1.copyUTF8String(&u);

    markdown::Document doc;
    
    std::istringstream instream(std::string((const char *)u.c_str(), u.length()));
    doc.read(instream);
    
    std::ostringstream outstream;
    doc.write(outstream);
    
    std::string dst = outstream.str();
    returnValue.setUTF8String((const uint8_t *)dst.c_str(), dst.length());
    
    returnValue.setReturn(pResult);

}

